### ISSUE TITLE
syntax error when starting anki

### ISSUE THREAD

**Issue by f-kessler** [brumar/anknotes#8]
Thanks for the useful tool!

After installing anknotes, I get a syntax error when I start anki. Import from evernote is working nevertheless.

This is what I get:

Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 39, in loadAddons
    __import__(file.replace(".py", ""))
  File "/home/pennywise/Anki/addons/anknotes_start.py", line 7, in <module>
    from anknotes import __main__
  File "/home/pennywise/Anki/addons/anknotes/anknotes/__main__.py", line 20
    <<<<<<< HEAD:Evernote.py
     ^
SyntaxError: invalid syntax

**Comment by f-kessler** [comment]
With the files in anknotes.zip it's working...

**Comment by brumar** [comment]
Hi and thank you for your review. [Scriptkiddi] (https://github.com/Scriptkiddi/anknotes) has put a lot of work to provide a new version to handle in a more secure and Evernote-Friendly way the authorization of anknotes. But we got many portability problems. That partly explains why the project is in this incomplete stage. I think it will be fixed soon. The zip file must be an old version. The new version don't work on my computer. This being said, I should fix these stupid strings raised by merge conflict which caused you this error. If we don't find the solution for the last problem we have, I will correct this, but without warranty that it will work for you.

**Comment by aip1000** [comment]
Thanks for this tool. After fixing the merge conflict errors, I'm still getting an error 'oauth: No such module found'. Any idea how to fix this? I don't know Python otherwise I'd look into it myself :-/

**Comment by aip1000** [comment]
I should add, with the files in anknotes.zip I get an error. I pasted the developer token from evernote.com. 

Error:     raise result.userException
evernote.edam.error.ttypes.EDAMUserException: EDAMUserException(errorCode=2, parameter='authenticationToken')

**Comment by aip1000** [comment]
Sorry - just saw scriptkiddi's fork, which launches fine. You can ignore my comments
